/**
 * Maps canonical ingredient names (post-alias normalization) to grocery categories.
 * Categories: 'produce', 'protein', 'dairy', 'pantry', 'other'
 */
export const INGREDIENT_CATEGORIES: Map<string, string> = new Map([
  // === PROTEINS ===
  ['chicken breast', 'protein'],
  ['chicken thigh', 'protein'],
  ['chicken thighs', 'protein'],
  ['ground chicken', 'protein'],
  ['chicken', 'protein'],
  ['ground beef', 'protein'],
  ['beef', 'protein'],
  ['steak', 'protein'],
  ['ground turkey', 'protein'],
  ['turkey', 'protein'],
  ['salmon', 'protein'],
  ['shrimp', 'protein'],
  ['cod', 'protein'],
  ['tilapia', 'protein'],
  ['halibut', 'protein'],
  ['tuna', 'protein'],
  ['mahi mahi', 'protein'],
  ['sea bass', 'protein'],
  ['trout', 'protein'],
  ['pork', 'protein'],
  ['pork tenderloin', 'protein'],
  ['bacon', 'protein'],
  ['ham', 'protein'],
  ['sausage', 'protein'],
  ['lamb', 'protein'],
  ['bison', 'protein'],
  ['venison', 'protein'],
  ['duck', 'protein'],
  ['tofu', 'protein'],
  ['tempeh', 'protein'],
  ['edamame', 'protein'],
  ['lentils', 'protein'],
  ['chickpeas', 'protein'],
  ['black beans', 'protein'],
  ['kidney beans', 'protein'],
  ['white beans', 'protein'],
  ['navy beans', 'protein'],
  ['pinto beans', 'protein'],
  ['eggs', 'protein'],
  ['egg', 'protein'],

  // === PRODUCE ===
  ['garlic', 'produce'],
  ['onion', 'produce'],
  ['onions', 'produce'],
  ['red onion', 'produce'],
  ['green onion', 'produce'],
  ['scallion', 'produce'],
  ['shallot', 'produce'],
  ['shallots', 'produce'],
  ['ginger', 'produce'],
  ['lemon', 'produce'],
  ['lime', 'produce'],
  ['orange', 'produce'],
  ['lemon juice', 'produce'],
  ['lime juice', 'produce'],
  ['tomato', 'produce'],
  ['tomatoes', 'produce'],
  ['cherry tomatoes', 'produce'],
  ['grape tomatoes', 'produce'],
  ['bell pepper', 'produce'],
  ['red bell pepper', 'produce'],
  ['green bell pepper', 'produce'],
  ['yellow bell pepper', 'produce'],
  ['jalapeño', 'produce'],
  ['jalapeño pepper', 'produce'],
  ['serrano pepper', 'produce'],
  ['poblano pepper', 'produce'],
  ['spinach', 'produce'],
  ['kale', 'produce'],
  ['arugula', 'produce'],
  ['romaine', 'produce'],
  ['lettuce', 'produce'],
  ['mixed greens', 'produce'],
  ['broccoli', 'produce'],
  ['cauliflower', 'produce'],
  ['asparagus', 'produce'],
  ['zucchini', 'produce'],
  ['yellow squash', 'produce'],
  ['butternut squash', 'produce'],
  ['spaghetti squash', 'produce'],
  ['eggplant', 'produce'],
  ['mushroom', 'produce'],
  ['mushrooms', 'produce'],
  ['cremini mushrooms', 'produce'],
  ['shiitake mushrooms', 'produce'],
  ['portobello mushrooms', 'produce'],
  ['carrot', 'produce'],
  ['carrots', 'produce'],
  ['celery', 'produce'],
  ['cucumber', 'produce'],
  ['avocado', 'produce'],
  ['sweet potato', 'produce'],
  ['potato', 'produce'],
  ['russet potato', 'produce'],
  ['red potato', 'produce'],
  ['beet', 'produce'],
  ['beets', 'produce'],
  ['radish', 'produce'],
  ['turnip', 'produce'],
  ['parsnip', 'produce'],
  ['corn', 'produce'],
  ['green beans', 'produce'],
  ['snap peas', 'produce'],
  ['snow peas', 'produce'],
  ['peas', 'produce'],
  ['bok choy', 'produce'],
  ['cabbage', 'produce'],
  ['brussels sprouts', 'produce'],
  ['artichoke', 'produce'],
  ['fennel', 'produce'],
  ['leek', 'produce'],
  ['cilantro', 'produce'],
  ['parsley', 'produce'],
  ['basil', 'produce'],
  ['mint', 'produce'],
  ['thyme', 'produce'],
  ['rosemary', 'produce'],
  ['sage', 'produce'],
  ['dill', 'produce'],
  ['chives', 'produce'],
  ['apple', 'produce'],
  ['banana', 'produce'],
  ['strawberry', 'produce'],
  ['strawberries', 'produce'],
  ['blueberries', 'produce'],
  ['raspberries', 'produce'],
  ['blackberries', 'produce'],
  ['mango', 'produce'],
  ['pineapple', 'produce'],
  ['peach', 'produce'],
  ['pear', 'produce'],
  ['grapes', 'produce'],
  ['watermelon', 'produce'],
  ['coconut', 'produce'],

  // === DAIRY ===
  ['butter', 'dairy'],
  ['ghee', 'dairy'],
  ['milk', 'dairy'],
  ['heavy cream', 'dairy'],
  ['heavy whipping cream', 'dairy'],
  ['sour cream', 'dairy'],
  ['cream cheese', 'dairy'],
  ['cheddar cheese', 'dairy'],
  ['mozzarella', 'dairy'],
  ['parmesan', 'dairy'],
  ['feta cheese', 'dairy'],
  ['goat cheese', 'dairy'],
  ['ricotta', 'dairy'],
  ['cottage cheese', 'dairy'],
  ['greek yogurt', 'dairy'],
  ['yogurt', 'dairy'],
  ['half and half', 'dairy'],
  ['cream', 'dairy'],
  ['cheese', 'dairy'],
  ['provolone', 'dairy'],
  ['swiss cheese', 'dairy'],
  ['brie', 'dairy'],
  ['gruyere', 'dairy'],
  ['mascarpone', 'dairy'],
  ['crème fraîche', 'dairy'],
  ['queso fresco', 'dairy'],
  ['cotija cheese', 'dairy'],

  // === PANTRY ===
  ['olive oil', 'pantry'],
  ['extra virgin olive oil', 'pantry'],
  ['avocado oil', 'pantry'],
  ['coconut oil', 'pantry'],
  ['sesame oil', 'pantry'],
  ['vegetable oil', 'pantry'],
  ['cooking spray', 'pantry'],
  ['salt', 'pantry'],
  ['pepper', 'pantry'],
  ['black pepper', 'pantry'],
  ['red pepper flakes', 'pantry'],
  ['cumin', 'pantry'],
  ['paprika', 'pantry'],
  ['smoked paprika', 'pantry'],
  ['turmeric', 'pantry'],
  ['coriander', 'pantry'],
  ['cinnamon', 'pantry'],
  ['chili powder', 'pantry'],
  ['cayenne', 'pantry'],
  ['garlic powder', 'pantry'],
  ['onion powder', 'pantry'],
  ['oregano', 'pantry'],
  ['italian seasoning', 'pantry'],
  ['bay leaf', 'pantry'],
  ['bay leaves', 'pantry'],
  ['soy sauce', 'pantry'],
  ['tamari', 'pantry'],
  ['coconut aminos', 'pantry'],
  ['fish sauce', 'pantry'],
  ['worcestershire sauce', 'pantry'],
  ['hot sauce', 'pantry'],
  ['sriracha', 'pantry'],
  ['vinegar', 'pantry'],
  ['apple cider vinegar', 'pantry'],
  ['red wine vinegar', 'pantry'],
  ['balsamic vinegar', 'pantry'],
  ['rice vinegar', 'pantry'],
  ['white wine vinegar', 'pantry'],
  ['chicken broth', 'pantry'],
  ['beef broth', 'pantry'],
  ['vegetable broth', 'pantry'],
  ['chicken stock', 'pantry'],
  ['beef stock', 'pantry'],
  ['vegetable stock', 'pantry'],
  ['coconut milk', 'pantry'],
  ['coconut cream', 'pantry'],
  ['tomato paste', 'pantry'],
  ['tomato sauce', 'pantry'],
  ['diced tomatoes', 'pantry'],
  ['crushed tomatoes', 'pantry'],
  ['whole peeled tomatoes', 'pantry'],
  ['canned tomatoes', 'pantry'],
  ['flour', 'pantry'],
  ['all-purpose flour', 'pantry'],
  ['almond flour', 'pantry'],
  ['rice flour', 'pantry'],
  ['cornstarch', 'pantry'],
  ['arrowroot', 'pantry'],
  ['baking powder', 'pantry'],
  ['baking soda', 'pantry'],
  ['sugar', 'pantry'],
  ['brown sugar', 'pantry'],
  ['honey', 'pantry'],
  ['maple syrup', 'pantry'],
  ['agave', 'pantry'],
  ['rice', 'pantry'],
  ['white rice', 'pantry'],
  ['brown rice', 'pantry'],
  ['jasmine rice', 'pantry'],
  ['basmati rice', 'pantry'],
  ['quinoa', 'pantry'],
  ['pasta', 'pantry'],
  ['spaghetti', 'pantry'],
  ['penne', 'pantry'],
  ['oats', 'pantry'],
  ['rolled oats', 'pantry'],
  ['bread crumbs', 'pantry'],
  ['panko', 'pantry'],
  ['tortillas', 'pantry'],
  ['corn tortillas', 'pantry'],
  ['flour tortillas', 'pantry'],
  ['almonds', 'pantry'],
  ['walnuts', 'pantry'],
  ['cashews', 'pantry'],
  ['pecans', 'pantry'],
  ['pine nuts', 'pantry'],
  ['sunflower seeds', 'pantry'],
  ['pumpkin seeds', 'pantry'],
  ['sesame seeds', 'pantry'],
  ['flaxseed', 'pantry'],
  ['chia seeds', 'pantry'],
  ['almond butter', 'pantry'],
  ['peanut butter', 'pantry'],
  ['tahini', 'pantry'],
  ['dijon mustard', 'pantry'],
  ['mustard', 'pantry'],
  ['mayonnaise', 'pantry'],
  ['ketchup', 'pantry'],
  ['salsa', 'pantry'],
  ['hummus', 'pantry'],
  ['miso paste', 'pantry'],
  ['miso', 'pantry'],
  ['nutritional yeast', 'pantry'],
  ['capers', 'pantry'],
  ['olives', 'pantry'],
  ['sun-dried tomatoes', 'pantry'],
  ['roasted red peppers', 'pantry'],
  ['artichoke hearts', 'pantry'],
  ['canned salmon', 'pantry'],
  ['canned tuna', 'pantry'],
  ['vanilla extract', 'pantry'],
  ['cocoa powder', 'pantry'],
  ['chocolate chips', 'pantry'],
  ['dried cranberries', 'pantry'],
  ['raisins', 'pantry'],
  ['dried apricots', 'pantry'],

  // === PRODUCE (additional) ===
  ['orange zest', 'produce'],
  ['orange juice', 'produce'],
  ['navel orange', 'produce'],

  // === PROTEIN (additional) ===
  ['kidney beans', 'protein'],
  ['salmon fillet', 'protein'],
  ['strip steak', 'protein'],

  // === OTHER (water — will be auto-omitted by isWater check) ===
  ['water', 'other'],

  // === PANTRY (additional) ===
  ['truffle oil', 'pantry'],
  ['vanilla bean paste', 'pantry'],
  ['almond milk', 'pantry'],
  ['pistachios', 'pantry'],
  ['hemp seeds', 'pantry'],
  ['rolled oats', 'pantry'],
  ['5 grain cereal', 'pantry'],
  ['nutmeg', 'pantry'],
  ['ground ginger', 'pantry'],
  ['cocoa powder', 'pantry'],
]);

export function classifyIngredient(canonicalName: string): string {
  const key = canonicalName.toLowerCase().trim();
  return INGREDIENT_CATEGORIES.get(key) ?? 'other';
}
